### PR TITLE
Deploying

### PR DESCRIPTION
**Pull request by 2004-okari**
- This project was deployed using GitHub pages.

### CODE REVIEW

**Review by stanleySimeon — CHANGES_REQUESTED** [review]
# Hi @2004-okari, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all linters checks passed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Ofarouq310 — COMMENTED** [review]
Hi @2004-okari,✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

giphy

## 🔴 Invalid Code Review Request

- You have submitted a project, that fails linters, kindly fix your `Stylelint` and you can ignore `Webhint` for now, as it is a common error among students nowadays and we let it slide.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @2004-okari 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- The last reviewer asked you to ignore only the Webhint linters error, but you removed the Lighthouse linters checks also. Kindly return it. Allow all linters checks to run. If Webhint fails, you can submit the project like that. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by joskalenda — CHANGES_REQUESTED** [review]
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @2004-okari , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
|  |

## Highlights

- [ ]... ✅ Great readme file

## Required Changes ♻️

- [ ] I have checked all of these parts and I did not see where is the link to the deployment, would you please update any of these places with the link to the online version?



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by 2004-okari** [comment]
Invalid link

**Comment by ahmetbozaci** [comment]
### Hello @2004-okari 
### _This is an additional review as a result of the second opinion request._ 

- Your pull request, `deploy_webpage`, was opened from the `main` branch, which is incorrect according to the established flow.


- In your pull request, the `main` branch appears to be treated as a feature branch, while the `deploy_webpage` branch is being treated as the main branch. When code reviewers assess the changes, they are reviewing the feature branch, which is actually the main branch in your pull request. Additionally, the main branch lacks a live demo link.

- [ ] I kindly request that you update the flow of the pull request and resubmit it for review. For more information about the GitHub flow, please refer to this [link](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md#:~:text=Make%20sure%20that%20you%20used%20correct%20flow%20(Github%20Flow.), which is already mentioned in the requirements.









___



### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by 2004-okari** [comment]
I figured that and created a new pull request since one cant change the feature branch. Only the base brach can be edited. Thank you for the feedback!

**Pull request closed without merging**
